entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: "info@zatha.in"
      storage: "/letsencrypt/acme.json"
      tlsChallenge: {}

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic_config.yml
    watch: true

http:
  middlewares:
    secure-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customRequestHeaders:
          X-Forwarded-Proto: https
