name: Deployment

on:
  push:
    branches: [ main ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code-repository
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
