name: Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy_to_ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key for EC2
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: SSH into EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.127.138.53 << 'EOF'
            # Install Docker and Docker Compose (if not already installed)
            # sudo apt-get update
            # sudo apt-get install -y docker.io curl git

            # Install Docker Compose (if not already installed)
            # sudo curl -SL https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-linux-$(uname -m) -o /usr/local/lib/docker/compose
            # sudo chmod +x /usr/local/lib/docker/compose
            # sudo ln -s /usr/local/lib/docker/compose /usr/bin/docker-compose

            if [ -d "/home/ubuntu/zatha.in" ]; then
              echo "Repository folder exists, pulling the branch."
            else
              echo "Repository folder does not exist, cloning the repository."
              git clone https://github.com/zathazass/zatha.in.git /home/ubuntu/zatha.in
            fi

            # Navigate to the project directory
            cd /home/ubuntu/zatha.in

            # Pulling the latest changes
            git pull

            # Build and start the containers using Docker Compose (direct from code)
            sudo docker compose down  # Stop and remove existing containers (if any)
            sudo docker compose up --build -d  # Build and start containers in detached mode

            # Optionally, remove old/dangling images to free space
            sudo docker image prune -f
          EOF
